name: ci

on:
  push:
    branches:
      - "*"  # run forbranches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: orders
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Unit Tests
        run: mvn -q test

      - name: Integration Tests
        run: mvn integration-test
        
      - name: Jfrog attemps Action
         # You may pin to the exact commit or the version.
         # uses: ruben-baez-mojix-com/jfrog-deployment@1d9b36340a1c49d08dfb1cc18556208153a23315
        uses: ruben-baez-mojix-com/jfrog-deployment@v1.0.2
        with:
        # Jfrog username
         username: admin
         # Jfrog password
         password: password
         # Artifact name
         artifact: # optional
         # URL where artifact will be deployed
         url: http://172.16.238.30:8082/artifactory/orders-demo/
         # expected time for artifact deployment
        
